Metrics/AbcSize:
  Max: 18
  Exclude:
    - 'test/integratoin/**/*_test.rb'

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 11
  Exclude:
    - 'test/integratoin/**/*_test.rb'

Style/Documentation:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/TrivialAccessors:
  AllowDSLWriters: true

Style/MethodCalledOnDoEndBlock:
  Enabled: true

Style/Send:
  Enabled: false
 
